### ISSUE TITLE
Text overflow outside the border

### ISSUE THREAD

**Issue by the7th** [ammezie/openlaravel#1]
Hi, I saw this when I opened your website (look at the arrows):

![screenshot-openlaravel com 2016-08-10 19-16-52](https://cloud.githubusercontent.com/assets/2613772/17551874/2c7b6bb2-5f2f-11e6-8371-7e1999dfcd9d.png)

It only happened for description that is too long I think. And yeah, on the right side as well.

**Comment by ammezie** [comment]
Thanks for pointing this out. Fixed it.
