### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by Muhanna02** [ammezie/openlaravel#10]
Hello again 

can you please explain how to set Algolia or any other thing that you have missed in installation guide ..!

**Comment by ammezie** [comment]
I have updated the readme.

**Comment by Muhanna02** [comment]
thx 

now the algolia worked but when I choose a project I got 

<img width="1042" alt="screen shot 2017-06-28 at 7 16 59 pm" src="https://user-images.githubusercontent.com/19315628/27648224-87402dda-5c36-11e7-820d-2c0fce6a68f4.png">
<img width="1102" alt="screen shot 2017-06-28 at 7 17 11 pm" src="https://user-images.githubusercontent.com/19315628/27648225-878e21fc-5c36-11e7-92c5-b80988e5bbaa.png">

**Comment by ammezie** [comment]
Yeah, you also need to create a GitHub app and add the app key to `.env`. I will update the readme to include this

**Comment by Muhanna02** [comment]
Good , also about the user registration I didn't find any route for that 

<img width="907" alt="screen shot 2017-06-28 at 9 16 43 pm" src="https://user-images.githubusercontent.com/19315628/27653224-1c346c84-5c47-11e7-90c2-e9b87aa76462.png">

**Comment by ammezie** [comment]
I have updated the readme to include the GitHub token.
