### ISSUE TITLE
After submitting package all fields value get deleted if validation is not cleared.

### ISSUE THREAD

**Issue by Modelizer** [ammezie/openlaravel#3]
Hi,
1. Submit a new [package](http://openlaravel.com/submit-project).
2. Enter an invalid value in any field.
3. Submit the form.
4. You will see due to one field is invalid, all field's value disappears.

It should populate all value.

**Comment by ammezie** [comment]
Fixed. Thanks for pointing this out.

**Comment by Modelizer** [comment]
Welcome. :)
