### ISSUE TITLE
Migration not working but throwing errors

### ISSUE THREAD

**Issue by minisoftgroup** [ammezie/openlaravel#4]
C:\wamp\www\McDiscovery>php artisan migrate --force

  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'discovery.projec
  ts' doesn't exist (SQL: select count(*) as aggregate from `projects` where
  `status` = 1)

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dis

**Comment by ammezie** [comment]
A quick question, why are you forcing the migration?
