### ISSUE TITLE
Cloning and installing the repo does not work as intented

### ISSUE THREAD

**Issue by ppshobi** [ammezie/openlaravel#5]
**To reproduce issue**

- clone the repo,
- set up a new DB credentials
- try issuing any artisan command say `migrate`

It throws an exception stating that  **Base table or view not found:**

This issue is because of the code inside the `app/Providers/AppServiceProvider.php` 's `boot` method

```
public function boot()
{
        view()->share('projectsCount', Project::where('status', 1)->count());
 }

```
I think this code tries to gather information even before the migration is run (It Even makes it impossible to execute any artisan commands so as for `migrating` ). so it says the projects table is not found.
I could workaround this issue by commenting the section for a moment, run the migration and then uncomment the issue. 
But a fix for this would be placing this code somewhere else. Can anyone suggest an idea?

**Comment by ammezie** [comment]
Yeah, I'm aware of this. A fix for it will be to remove the code completely from `app/Providers/AppServiceProvider.php`. In fact, the new design (which I already started working on in the `develop` branch) is no longer using the above code.

**Comment by ppshobi** [comment]
Actually, I can see the same code in the develop branch also :|. But now the exception thrown is different, the `Illuminate\Notifications\NotificationServiceProvider` is not found. can you provide some info about correcting that?

**Comment by ammezie** [comment]
Actually, I have fixed these issues in my local copy. Will push so you can fork again.
