### ISSUE TITLE
generating search 

### ISSUE THREAD

**Issue by Muhanna02** [ammezie/openlaravel#9]
Hello bro 

First of all thank you .Second I have installed it and integrated it with algolia,every thing good but the generating search still not working

**Comment by ammezie** [comment]
What do you mean by generating search still not working, are you getting an error or something?

**Comment by ppshobi** [comment]
@Muhanna02  Please provide the inputs you have tried and steps to reproduce the issues. so that we can fix the issue. be it screenshots, exceptions, stack traces etc...

**Comment by Muhanna02** [comment]
I mean while I'm searching it should display the projects ...I have uploaded a screenshot 
<img width="1099" alt="screen shot 2017-06-20 at 1 15 32 pm" src="https://user-images.githubusercontent.com/19315628/27328416-c953c240-55ba-11e7-8156-e71c5f00ac9a.png">
although I have set the alogolia properly 
<img width="1243" alt="screen shot 2017-06-20 at 1 17 40 pm" src="https://user-images.githubusercontent.com/19315628/27328488-fb226ad8-55ba-11e7-9f4a-56693204748e.png">

**Comment by ammezie** [comment]
Check your console to see if it throwing errors. Also, make you enter your Algolia credentials in `.env`

**Comment by Muhanna02** [comment]
nothing in the console ..!! . I have set Algolia credentials in .env and it's updated once I created a project

**Comment by ammezie** [comment]
Thats wierd.

**Comment by Muhanna02** [comment]
<img width="1259" alt="screen shot 2017-06-23 at 1 10 13 am" src="https://user-images.githubusercontent.com/19315628/27458275-ddfd2dec-57b0-11e7-8121-810006d16ff1.png">
when I click on any project I got this error !!
